library(dplyr)
library(dbplyr)
library(duckdb)

con <- dbConnect(duckdb(), "delta_hedged_returns.duckdb", read_only = FALSE)
option_price_tbl <- tbl(con, "option_price")
security_price_tbl <- tbl(con, "security_price") 
ff_data_tbl <- tbl(con, "ff_rates")


#SPX secid
target_secids <- 108105

# First get security prices and risk-free rates
security_data <- security_price_tbl |> 
 select(secid, date, close) |>
 rename(stock_price = close)

# Get risk-free rates for no-arbitrage bounds calculation
rf_data <- ff_data_tbl |>
 select(date, rf_daily)

# Filter option data following paper's criteria

option_data <- option_price_tbl |>
 filter(secid == target_secids) |> 
 # Join with stock prices and risk-free rates for no-arbitrage checks
 inner_join(security_data, by = c("secid", "date")) |>
 inner_join(rf_data, by = "date") |>
 # PAPER (Page 223): "Option returns that we compute are based on the midpoints"
 # "Almost always, with an occasional client limit order, option returns that we 
 # compute are based on the midpoints generated by these OMMs' computer programs"
 mutate(
   midpoint = (best_bid + best_offer) / 2,
   spread = best_offer - best_bid,
   spread_pct = spread / midpoint,
   strike = strike_price / 1000,  # Convert strike price from IvyDB format
   
   # Calculate days to expiration for no-arbitrage bounds
   days_to_expiry = as.integer(exdate - date),
   time_to_expiry = days_to_expiry / 365.0,
   
   # Calculate intrinsic value for no-arbitrage check
   intrinsic_value = case_when(
     cp_flag == "C" ~ pmax(stock_price - strike, 0),
     cp_flag == "P" ~ pmax(strike - stock_price, 0),
     TRUE ~ 0
   ),
   
   # Calculate present value of strike for bounds
   pv_strike = strike * exp(-rf_daily * time_to_expiry),
   
   # No-arbitrage bounds for calls
   call_lower_bound = pmax(stock_price - pv_strike, 0),
   call_upper_bound = stock_price,
   
   # No-arbitrage bounds for puts  
   put_lower_bound = pmax(pv_strike - stock_price, 0),
   put_upper_bound = pv_strike
 ) |>
 # PAPER (Page 223): "We apply standard data filters. To compute option return over 
 # a given time period, we exclude option contracts for which at the beginning of 
 # this period:"
 filter(
   # PAPER: "the bid price is greater than or equal to the ask price"
   # (We filter the opposite: bid < ask)
   best_bid < best_offer,
   
   # PAPER: "the bid price is not available or is below 50 cents"
   !is.na(best_bid) & !is.na(best_offer),
   best_bid >= 0.50,
   
   # PAPER: "the quoted bid-ask spread is over 70% of the midpoint, or three dollars"
   spread_pct <= 0.70,
   spread <= 3.00,
   
   # PAPER: "option delta cannot be computed"
   !is.na(delta),
   
   # PAPER (Table 1): "All deltas includes options with an absolute delta between 0.1 and 0.9"
   abs(delta) >= 0.1 & abs(delta) <= 0.9,
   
   # PAPER: "option prices violate no-arbitrage bounds"
   # Option price must be at least intrinsic value
   midpoint >= intrinsic_value,
   
   # Calls must be within no-arbitrage bounds
   (cp_flag != "C" | (midpoint >= call_lower_bound & midpoint <= call_upper_bound)),
   
   # Puts must be within no-arbitrage bounds  
   (cp_flag != "P" | (midpoint >= put_lower_bound & midpoint <= put_upper_bound)),
   
   # Additional no-arbitrage checks
   (cp_flag != "C" | midpoint < stock_price),
   (cp_flag != "P" | midpoint < strike)
 ) |>
 # Set option_price to midpoint as per paper
 mutate(option_price = midpoint) |>
 select(secid, date, optionid, symbol, cp_flag, strike, exdate, 
        option_price, delta, stock_price, days_to_expiry, time_to_expiry,
        best_bid, best_offer, volume, impl_volatility)

# Count filtered options
print("Counting filtered observations...")
option_count <- option_data |> 
 summarise(
   total = n(),
   calls = sum(cp_flag == "C", na.rm = TRUE),
   puts = sum(cp_flag == "P", na.rm = TRUE)
 ) |> 
 collect()

print(paste("Total filtered options:", option_count$total))
print(paste("  Calls:", option_count$calls))
print(paste("  Puts:", option_count$puts))

#Calculate delta-hedged returns

# PAPER (Page 223): "Delta hedged option returns are computed using deltas from 
# the BSM model; the hedge is revised five times a day, about every 80 min."
# Note: With daily data, we cannot hedge intraday, but we follow the same formulas

returns_data <- option_data |>
 arrange(secid, optionid, date) |>
 group_by(secid, optionid) |>
 mutate(
   prev_option_price = lag(option_price),
   prev_stock_price = lag(stock_price),
   prev_delta = lag(delta),
   
   # Calculate changes
   option_change = option_price - prev_option_price,
   stock_change = stock_price - prev_stock_price,
   
   # PAPER (Page 223, Equation 1): 
   # "P&Lt = Ct - Ct-1 - Δt-1*(St - St-1)"
   # "where Δ is option delta and St is the underlying price at time t"
   pnl = option_change - (prev_delta * stock_change),
   
   # PAPER (Page 223, Equation 2):
   # "Option delta hedged return is then computed as: Rett = P&Lt / Ct-1"
   delta_hedged_return = pnl / prev_option_price,
   
   # PAPER (Page 223, Equation 3): "The deleveraged option return for Rett is defined as:
   # RetDL_t = Rett / ψt-1, where ψt-1 = |Δt-1*St-1/Ct-1|"
   # "ψt-1 is the deleveraging factor, which is usually well above five"
   leverage_factor = abs(prev_delta * prev_stock_price / prev_option_price),
   deleveraged_return = delta_hedged_return / leverage_factor
 ) |>
 filter(!is.na(delta_hedged_return)) |>
 # Remove extreme returns likely due to data errors
 filter(abs(delta_hedged_return) < 10) |>  
 ungroup()

# PAPER (Table 1): "Summary statistics for average day and night delta hedged option 
# returns cover mean, standard deviation, 1st, 50th, and 99th percentiles"

# Overall statistics
overall_stats <- returns_data |>
 summarise(
   mean_return = mean(delta_hedged_return, na.rm = TRUE) * 100,
   std_return = sd(delta_hedged_return, na.rm = TRUE) * 100,
   median_return = median(delta_hedged_return, na.rm = TRUE) * 100,
   q01 = quantile(delta_hedged_return, 0.01) * 100,
   q99 = quantile(delta_hedged_return, 0.99) * 100,
   n_obs = n()
 ) |>
 collect()

print("\nOVERALL DELTA-HEDGED RETURNS:")
print(overall_stats)

# PAPER (Table 1): Results split by "Puts" and "Calls"
cp_stats <- returns_data |>
 group_by(cp_flag) |>
 summarise(
   mean_return = mean(delta_hedged_return, na.rm = TRUE) * 100,
   std_return = sd(delta_hedged_return, na.rm = TRUE) * 100,
   median_return = median(delta_hedged_return, na.rm = TRUE) * 100,
   q01 = quantile(delta_hedged_return, 0.01) * 100,
   q99 = quantile(delta_hedged_return, 0.99) * 100,
   n_obs = n()
 ) |>
 collect()

print("\nRETURNS BY OPTION TYPE (Replicating Table 1):")
print(cp_stats)
